### ISSUE TITLE
Monitoring 8.6 SNAPSHOT to see that metricbeat doesn't crush cloudbeat

### ISSUE THREAD

**Issue by ofiriro3** [elastic/cloudbeat#638]
**Motivation**
Verify that the agent doesn't crush due to metricbeats nil pointer exception.

**Description**
During my on-call week, I was assigned to run and monitor a BC9 environment. While monitoring the environment I saw that metricbeat encountered a nil pointer exception. After some time metricbeat caused the agent to restart and as a result of it, cloudbeat was restarted as well.

After discussing with the `elastic-agent` team, they said that the problem was solved, and we were already merged into the new 8.6 SNAPSHOT. 
We would like to verify that the fix indeed fixed the issue.

Related task- 
https://github.com/elastic/security-team/issues/5577

**Comment by ofiriro3** [comment]
Error example
```
[elastic_agent.metricbeat][info] metricbeat start running.
13:47:48.676
elastic_agent
[elastic_agent][info] Component state changed http/metrics-monitoring (STARTING->HEALTHY): Healthy: communicating with pid '4370'
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] panic: runtime error: invalid memory address or nil pointer dereference
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x55ccb50a6b10]
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] goroutine 2201 [running]:
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/metricbeat/cmd.metricbeatCfg(0x0, 0xc000a11968?)
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/metricbeat/cmd/agent.go:25 +0x50
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.(*TransformRegister).Transform(0x5?, 0x19?, 0x200000002?)
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/generate.go:60 +0x103
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.generateBeatConfig(0xc000e5d270?, 0xc000a11a98?)
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/generate.go:232 +0x26
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).reloadInputs(0xc000bfafc0, {0xc000116d38, 0x1, 0x0?})
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:540 +0x155
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).reload(0xc000bfafc0, 0xc000a11da8?)
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:450 +0x56b
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).unitListen(0xc000bfafc0)
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:379 +0x405
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] created by github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).Start
13:47:48.774
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:178 +0x116
13:47:48.778
elastic_agent
[elastic_agent][error] Component state changed beat/metrics-monitoring (HEALTHY->FAILED): Failed: pid '4369' exited with code '2'
13:47:48.778
elastic_agent
[elastic_agent][error] Unit state changed beat/metrics-monitoring-metrics-monitoring-beats (STARTING->FAILED): Failed: pid '4369' exited with code '2'
13:47:48.778
elastic_agent
[elastic_agent][error] Unit state changed beat/metrics-monitoring (STARTING->FAILED): Failed: pid '4369' exited with code '2'
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] panic: runtime error: invalid memory address or nil pointer dereference
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x564384ea6b10]
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] goroutine 2181 [running]:
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/metricbeat/cmd.metricbeatCfg(0x0, 0xc000698968?)
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/metricbeat/cmd/agent.go:25 +0x50
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.(*TransformRegister).Transform(0x5?, 0x19?, 0x200000002?)
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/generate.go:60 +0x103
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.generateBeatConfig(0xc001880fe0?, 0xc000698a98?)
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/generate.go:232 +0x26
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).reloadInputs(0xc00108a240, {0xc0002870c0, 0x1, 0x0?})
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:540 +0x155
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).reload(0xc00108a240, 0xc000698da8?)
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:450 +0x56b
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).unitListen(0xc00108a240)
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:379 +0x405
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] created by github.com/elastic/beats/v7/x-pack/libbeat/management.(*BeatV2Manager).Start
13:47:48.779
elastic_agent.metricbeat
[elastic_agent.metricbeat][error] github.com/elastic/beats/v7/x-pack/libbeat/management/managerV2.go:178 +0x116
13:47:48.783
elastic_agent
[elastic_agent][error] Component state changed http/metrics-monitoring (HEALTHY->FAILED): Failed: pid '4370' exited with code '2'
```

**Comment by ofiriro3** [comment]
I have just deployed an environment for 8.6 SNAPSHOT.
I'll monitor the environment and update here if the problem was resolved or not

**Comment by ofiriro3** [comment]
Intervals look legit, I haven't encountered any unexpected behavior : 

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/19221736/210521840-612d72c5-1ddd-4e9b-a845-49d54d106239.png">

When looking at the logs I see that the nil pointer exception bug was indeed fixed ([PR](https://github.com/elastic/beats/issues/34137).

I did notice two different errors, but they didn't cause the agent to restart.
1. 
```
[elastic_agent.metricbeat][error] Error fetching data for metricset beat.stats: monitored beat is using Elasticsearch output but cluster UUID cannot be determined
```
2. 
[elastic_agent.metricbeat][warn] read token request for getting IMDSv2 token returns empty: Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers). No token in the metadata request will be used.
[elastic_agent.metricbeat][info] metricbeat stopped.
10:52:17.102
elastic_agent
[elastic_agent][info] Component state changed beat/metrics-monitoring (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '31881' exited with code '0'
```
I contacted the relevant team.

I am closing this issue.

FYI 
@kfirpeled @eyalkraft @oren-zohar @tehilashn
