### ISSUE TITLE
Scanning encrypted EBS snapshots

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#733]

**Comment by oren-zohar** [comment]
- Additional info from: https://github.com/elastic/cloudbeat/issues/737
> **Motivation**
- Encrypted volumes for EC2 are a common practice that we have to support.
- AWS [docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-creating-snapshot.html) says that snapshots that are taken from encrypted volumes are automatically encrypted.
- The snapshot read operation, [GetSnapshotBlock](https://docs.aws.amazon.com/ebs/latest/APIReference/API_GetSnapshotBlock.html), says that if the specified snapshot is encrypted, you must have permission to use the KMS key that was used to encrypt the snapshot.
- Since the elastic-agent role is dynamically created from a CloudFormation template, it is possible to grant permissions to the KMS key that is used to encrypt the snapshots.
- In [EBS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html) you can find that the default encryption key has an alias `alias/aws/ebs`.
- The last phase will be granting the elastic-agent role access to this key as described [here](https://stackoverflow.com/questions/54430743/how-to-get-an-aws-ssm-key-arn-from-an-alias-using-cloudformation).

**Definition of done**
Update elastic-agent CloudFormation template:
- [ ] Find the key ARN used to encrypt EBS volumes
- [ ] Grant permissions to the elastic-agent role so it could decrypt EBS volumes

**Comment by masahiro331** [comment]
Hi Elastic beat team.

I'm contributor for Trivy's VM scan feature.

EBS read processing used in Trivy's VM scan is implemented in this library.
https://github.com/masahiro331/go-ebs-file

If this issue can be improved on the library side, we welcome issues or PRs.
I would appreciate it if I could contribute something to this problem.

**Comment by amirbenun** [comment]
Latest update:
1. I created an encrypted EC2 instance using the default KMS key for EBS that I will try to scan.
2. I created two separate CloudFormation stacks, one has a `decrypt` permission to the key and the other doesn't.
3. I configured cloudbeat to only scan my EC2 instance (to avoid noise)

result:
- Both stacks generate the same error:
```
Partition error: filesystem error: unexpected fs error: new xfs filesystem error: failed to parse primary allocation group: failed to parse agf magic byte error: 00000000
```

I still don't know what went wrong, but I will keep looking.

**Comment by masahiro331** [comment]
Upon review of the error, it appears that the magic byte at the beginning of the file system superblock is correctly detected, and the subsequent parsing process is causing the error.
Since this error may be caused by go-xfs-filesystem, we would like to reproduce the verification environment, can you please share the cloudformation?

**Comment by amirbenun** [comment]
Update:
`ReadSector` was a static method with hard-coded sector size of 512.
Instead, I implemented the function as part of a new struct `sectorReader` that can accept `sectorSize`.
In my pr, I initialized the `sectorReader` with the sector size found in the superblock of the Allocation Group (AG).
Even after this change the parsing of XFS doesn't work and eventually ends up with a panic.
```
goroutine 1 [running]:
github.com/masahiro331/go-xfs-filesystem/xfs.(*FileSystem).parseXDB3Block(0x10a66c760?, {0x10a66c760?, 0x14000afdb30?})
        /Users/amir/Development/go/trivy/vendor/github.com/masahiro331/go-xfs-filesystem/xfs/inode.go:632 +0x298
github.com/masahiro331/go-xfs-filesystem/xfs.(*FileSystem).parseDir2Block(0x14001226300, {0x1400123aa00?, 0x140033342c8?, 0x102a9e860?, 0x38?})
        /Users/amir/Development/go/trivy/vendor/github.com/masahiro331/go-xfs-filesystem/xfs/inode.go:754 +0x3e0
github.com/masahiro331/go-xfs-filesystem/xfs.(*FileSystem).listEntries(0x14001226300?, 0x14000388a00?)
        /Users/amir/Development/go/trivy/vendor/github.com/masahiro331/go-xfs-filesystem/xfs/xfs.go:367 +0x494
github.com/masahiro331/go-xfs-filesystem/xfs.(*FileSystem).listFileInfo(0x140011afbf1?, 0x3?)
        /Users/amir/Development/go/trivy/vendor/github.com/masahiro331/go-xfs-filesystem/xfs/xfs.go:321 +0x28
github.com/masahiro331/go-xfs-filesystem/xfs.(*FileSystem).readDirEntry(0x14003334868?, {0x140011afbf0, 0x4})
        /Users/amir/Development/go/trivy/vendor/github.com/masahiro331/go-xfs-filesystem/xfs/xfs.go:297 +0x1e8
github.com/masahiro331/go-xfs-filesystem/xfs.(*FileSystem).ReadDir(0x3?, {0x140011afbf0, 0x4})
        /Users/amir/Development/go/trivy/vendor/github.com/masahiro331/go-xfs-filesystem/xfs/xfs.go:136 +0x24
io/fs.ReadDir({0x10a67f100, 0x14001226300}, {0x140011afbf0, 0x4})
        /Users/amir/.gvm/gos/go1.19.6/src/io/fs/readdir.go:30 +0x2b4
io/fs.walkDir({0x10a67f100, 0x14001226300}, {0x140011afbf0, 0x4}, {0x10a713e88, 0x14001b7ca80}, 0x14003334bf0)
        /Users/amir/.gvm/gos/go1.19.6/src/io/fs/walk.go:73 +0x110
io/fs.walkDir({0x10a67f100, 0x14001226300}, {0x10937d4c8, 0x1}, {0x10a712a30, 0x14000059e80}, 0x14003334bf0)
        /Users/amir/.gvm/gos/go1.19.6/src/io/fs/walk.go:87 +0x258
io/fs.WalkDir({0x10a67f100, 0x14001226300}, {0x10937d4c8, 0x1}, 0x14002786bf0)
        /Users/amir/.gvm/gos/go1.19.6/src/io/fs/walk.go:114 +0xc4
github.com/aquasecurity/trivy/pkg/fanal/walker.(*VM).diskWalk(0x14001918060, {0x10937d4c8, 0x1}, {0x10a71eaa0, 0x14000458a00})
        /Users/amir/Development/go/trivy/pkg/fanal/walker/vm.go:107 +0x1f4
github.com/aquasecurity/trivy/pkg/fanal/walker.(*VM).Walk(0x14001918060, 0x0?, {0x10937d4c8, 0x1}, 0x0?)
        /Users/amir/Development/go/trivy/pkg/fanal/walker/vm.go:78 +0xe8
github.com/aquasecurity/trivy/pkg/fanal/artifact/vm.(*Storage).Analyze(_, {_, _}, _)
        /Users/amir/Development/go/trivy/pkg/fanal/artifact/vm/vm.go:48 +0x154
github.com/aquasecurity/trivy/pkg/fanal/artifact/vm.(*EBS).Inspect(_, {_, _})
        /Users/amir/Development/go/trivy/pkg/fanal/artifact/vm/ebs.go:62 +0x13c
github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact({{_, _}, {_, _}}, {_, _}, {{0x1400127cf00, 0x2, 0x2}, {0x14000595500, ...}, ...})
        /Users/amir/Development/go/trivy/pkg/scanner/scan.go:144 +0x98
github.com/aquasecurity/trivy/pkg/commands/artifact.scan({_, _}, {{{0x107f3ba05, 0xa}, 0x0, 0x0, 0x0, 0x0, 0x1a3185c5000, {0x14001c82500, ...}, ...}, ...}, ...)
        /Users/amir/Development/go/trivy/pkg/commands/artifact/run.go:688 +0x248
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact(_, {_, _}, {{{0x107f3ba05, 0xa}, 0x0, 0x0, 0x0, 0x0, 0x1a3185c5000, ...}, ...}, ...)
        /Users/amir/Development/go/trivy/pkg/commands/artifact/run.go:265 +0x94
github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).ScanVM(_, {_, _}, {{{0x107f3ba05, 0xa}, 0x0, 0x0, 0x0, 0x0, 0x1a3185c5000, ...}, ...})
        /Users/amir/Development/go/trivy/pkg/commands/artifact/run.go:261 +0xb8
github.com/aquasecurity/trivy/pkg/commands/artifact.Run({_, _}, {{{0x107f3ba05, 0xa}, 0x0, 0x0, 0x0, 0x0, 0x1a3185c5000, {0x14001c82500, ...}, ...}, ...}, ...)
        /Users/amir/Development/go/trivy/pkg/commands/artifact/run.go:451 +0x2a0
github.com/aquasecurity/trivy/pkg/commands.NewVMCommand.func2(0x1400026f800, {0x140001cec30, 0x1, 0x5})
        /Users/amir/Development/go/trivy/pkg/commands/app.go:989 +0x22c
github.com/spf13/cobra.(*Command).execute(0x1400026f800, {0x140001cebe0, 0x5, 0x5})
        /Users/amir/Development/go/trivy/vendor/github.com/spf13/cobra/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x140002ec600)
        /Users/amir/Development/go/trivy/vendor/github.com/spf13/cobra/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/amir/Development/go/trivy/vendor/github.com/spf13/cobra/command.go:968
main.run()
        /Users/amir/Development/go/trivy/cmd/trivy/main.go:39 +0x164
main.main()
        /Users/amir/Development/go/trivy/cmd/trivy/main.go:21 +0x1c
```

**Comment by amirbenun** [comment]
As suggested by @tehilashn, it is worth checking which of our competitors can scan encrypted EC2s.
I will spend a few hours to read their documentation and map them.
